name: Post Daily Comment
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every day at midnight UTC
  issues:
    types:
      - labeled

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Post comment
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Developers reports for: $(date +"%Y-%m-%d")" > comment.txt
          commit_sha=$(git rev-parse HEAD)
          thread_id="https://github.com/IgorBialek/AnimeRefresher/discussions/2"  # Replace with the discussion thread ID
          api_url="https://api.github.com/repos/${{ github.repository }}/git/commits/${commit_sha}/comments"
          comment_body=$(cat comment.txt)
          curl -sSL -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "{\"body\":\"$comment_body\", \"thread_id\":\"$thread_id\"}" $api_url
